### ISSUE TITLE
Cannot subscribe to RSS-Feed

### ISSUE THREAD

**Issue by Kaligule** [amatriain/feedbunch#5]
The blog ist on <http://www.gewürzrevolver.de>.
I assume the error is because the umlaut ü in the domain. I was able to subscribe to it with feedly, though.

**Comment by amatriain** [comment]
Yes, the cause is definitely the non-ascii character in the URL. It seems that the URI module for ruby only supports URLs with ascii chars.

I think the URI module can be safely replaced with the [addressable](https://github.com/sporkmonger/addressable) gem, which supports [internationalized domain names](http://en.wikipedia.org/wiki/Internationalized_domain_name). This should be a quick fix.

**Comment by amatriain** [comment]
It wasn't so simple after all :sweat_smile: 

It should be fixed now. Unfortunately the feed for the blog at http://www.gewürzrevolver.de currently has no entries, but you can subscribe to it anyway. I've also subscribed to http://www.supportbär.de/ and http://bücher.ch/, and they work correctly. Perhaps you know of other examples of URLs with umlauts, I haven't found many.

The fix is not specific to URLs with umlauts, any internationalized URL (with non-ASCII characters) should be supported now.

Could you confirm if it works for you?

**Comment by Kaligule** [comment]
Works, thanks :+1:
